### ISSUE TITLE
Website Copy

### ISSUE THREAD

**Issue by katalist-innovations** [AndreBClark/dscvr#25]
### Needed Copy

- Event details on homepage

- A blurb about the large mailchimp signup on the contact page (something about how we want to be able to send them updates on the program)

- A couple of paragraphs about the graphic design and web program

- An intro paragraph to go on the portfolio page about the students (maybe something about our versatile skills) - might be able to find something on the welearndesign.com site about the program teaching a wide range of skill sets and how our class this year is diverse in skill sets (we do web, packaging, typography, illustration, etc.)

- A paragraph encouraging people to let us know they're attending on our facebook event

- Any other copy chunks you think we need for places

**Ask others if you need help generating copy**

### Tasks

- [x] Create new branch from features/cards (call it "features/copy")

- [x] Create copy.html (this is where you'll populate the copy for now)

- [x] Gather information about the event (what, when, where, who) from the facebook event or from the social media team (Kallie & Rachel) and place in a `<p>` tag

- [x] Gather information about the Graphic/Web Design program (from welearndesign.com, facebook page) and place in `<p>` tags (break it up into different paragraphs however you see fit) 

- [x] Create portfolio page intro text (to eventually go at the top of portfolio page)

- [x] Indicate in comments around each` <p>` tag where you think each chunk of copy should go (for instance, event details go on homepage)

- [x] Create other needed copy and put into` <p>` tags
